name: CHARTextract
dependencies:
  - python=3.7
  - asn1crypto=0.24.0=py37_0
  - backcall=0.1.0=py37_0
  - bokeh=0.13.0=py37_0
  - certifi=2018.8.24=py37_1
  - cffi=1.11.5=py37h74b6da3_1
  - click=6.7=py37_0
  - cloudpickle=0.5.5=py37_0
  - colorama=0.3.9=py37_0
  - cryptography=2.3.1=py37h74b6da3_0
  - cytoolz=0.9.0.1=py37hfa6e2cd_1
  - dask=0.19.1=py37_0
  - dask-core=0.19.1=py37_0
  - decorator=4.3.0=py37_0
  - distributed=1.23.1=py37_0
  - heapdict=1.0.0=py37_2
  - idna=2.7=py37_0
  - ipykernel=4.9.0=py37_1
  - ipython=6.5.0=py37_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.12.1=py37_0
  - jupyter_client=5.2.3=py37_0
  - jupyter_core=4.4.0=py37_0
  - locket=0.2.0=py37_1
  - mkl_fft=1.0.4=py37h1e22a9b_1
  - mkl_random=1.0.1=py37h77b88f5_1
  - msgpack-python=0.5.6=py37he980bc4_1
  - numpy-base=1.15.2=py37h8128ebf_0
  - packaging=17.1=py37_0
  - pandas=0.23.4=py37h830ac7b_0
  - parso=0.3.1=py37_0
  - partd=0.3.8=py37_0
  - pickleshare=0.7.4=py37_0
  - pip=10.0.1=py37_0
  - prompt_toolkit=1.0.15=py37_0
  - psutil=5.4.7=py37hfa6e2cd_0
  - pycparser=2.18=py37_1
  - pygments=2.2.0=py37_0
  - pymysql=0.9.2=py37_0
  - pyodbc=4.0.24=py37h6538335_0
  - python-dateutil=2.7.3=py37_0
  - pytz=2018.5=py37_0
  - pyyaml=3.13=py37hfa6e2cd_0
  - pyzmq=17.1.2=py37hfa6e2cd_0
  - scikit-learn=0.19.1
  - setuptools=40.2.0=py37_0
  - simplegeneric=0.8.1=py37_2
  - sortedcontainers=2.0.5=py37_0
  - sqlalchemy=1.2.11=py37hfa6e2cd_0
  - tblib=1.3.2=py37_0
  - toolz=0.9.0=py37_0
  - tornado=5.1=py37hfa6e2cd_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.31.1=py37_0
  - wincertstore=0.2=py37_0
  - xlrd=1.1.0=py37_1
  - zict=0.1.3=py37_0
  - pip:
    - altgraph==0.15
    - cycler==0.10.0
    - django==2.1.3
    - et-xmlfile==1.0.1
    - future==0.16.0
    - jdcal==1.4
    - jinja2==2.10
    - kiwisolver==1.0.1
    - macholib==1.9
    - markupsafe==1.0
    - matplotlib==2.2.2
    - numpy==1.15.0
    - openpyxl==2.5.4
    - pefile==2017.11.5
    - pycountry==18.5.26
    - pyinstaller==3.4
    - pyparsing==2.2.0
    - pypiwin32==223
    - pywin32==223
    - pywin32-ctypes==0.2.0
    - scipy==1.1.0
    - six==1.11.0